// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package demoprobe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	demoprobeMapDemoProbeValue = "demo_probe_value"
	demoprobeMapDemoTrampoline = "demo_trampoline"
	demoprobeProgDemoprobe     = "demoprobe"
	demoprobeVarModulo         = "modulo"
)

// loadDemoprobe returns the embedded CollectionSpec for demoprobe.
func loadDemoprobe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DemoprobeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load demoprobe: %w", err)
	}

	return spec, err
}

// loadDemoprobeObjects loads demoprobe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*demoprobeObjects
//	*demoprobePrograms
//	*demoprobeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDemoprobeObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadDemoprobe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// demoprobeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type demoprobeSpecs struct {
	demoprobeProgramSpecs
	demoprobeMapSpecs
	demoprobeVariableSpecs
}

// demoprobeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type demoprobeProgramSpecs struct {
	Demoprobe *ebpf.ProgramSpec `ebpf:"demoprobe"`
}

// demoprobeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type demoprobeMapSpecs struct {
	DemoProbeValue *ebpf.MapSpec `ebpf:"demo_probe_value"`
	DemoTrampoline *ebpf.MapSpec `ebpf:"demo_trampoline"`
}

// demoprobeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type demoprobeVariableSpecs struct {
	Modulo *ebpf.VariableSpec `ebpf:"modulo"`
}

// demoprobeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDemoprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type demoprobeObjects struct {
	demoprobePrograms
	demoprobeMaps
	demoprobeVariables
}

func (o *demoprobeObjects) Close() error {
	return _DemoprobeClose(
		&o.demoprobePrograms,
		&o.demoprobeMaps,
	)
}

// demoprobeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDemoprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type demoprobeMaps struct {
	DemoProbeValue *ebpf.Map `ebpf:"demo_probe_value"`
	DemoTrampoline *ebpf.Map `ebpf:"demo_trampoline"`
}

func (m *demoprobeMaps) Close() error {
	return _DemoprobeClose(
		m.DemoProbeValue,
		m.DemoTrampoline,
	)
}

// demoprobeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadDemoprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type demoprobeVariables struct {
	Modulo *ebpf.Variable `ebpf:"modulo"`
}

// demoprobePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDemoprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type demoprobePrograms struct {
	Demoprobe *ebpf.Program `ebpf:"demoprobe"`
}

func (p *demoprobePrograms) Close() error {
	return _DemoprobeClose(
		p.Demoprobe,
	)
}

func _DemoprobeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed demoprobe_arm64_bpfel.o
var _DemoprobeBytes []byte
